version: '3.2'
services:
  app.authorizer:
    container_name: app.authorizer
    build:
      context: .
    env_file:
      - ./app/.env
    networks:
      - bubble
    ports:
      - 7777:80
    volumes:
      - ./app:/app
networks:
  bubble:
    external: true